### ISSUE TITLE
Select custom taxonomy?

### ISSUE THREAD

**Issue by tripod3d** [imath/bp-groups-taxo#24]
Is there a way that I can use an already in-use taxonomy linked to a custom post type?

Thanks.

**Comment by imath** [comment]
There is always a way. But the problem here is that it would create a mess with your WordPress because you can't "type" an object into the database that stores the object IDs that are linked to a custom taxonomy. As a result WordPress it would be difficult to know that an object ID is the ID of a WordPress Post or a BuddyPress group. Posts and Groups are in 2 distinct tables, so there can be a Post having the ID `1` and a Group having the ID `1`.

**Comment by tripod3d** [comment]
I just found forked version of multiple taxo allowed.
